#!/bin/bash -l
#
# CP2K on Piz Daint: 64 nodes, 1 MPI task per node, 12 OpenMP threads per task
#
#SBATCH --job-name=cp2k
#SBATCH --time=3:50:00
#SBATCH --nodes=27
#SBATCH --ntasks-per-node=12
#SBATCH --cpus-per-task=1
#SBATCH --account=s904
#SBATCH --partition=normal
#SBATCH --constraint=gpu
#SBATCH --array=0-38
#========================================
# load modules and run simulation


module load daint-gpu
module load CP2K
export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK:-1}
export CRAY_CUDA_MPS=1

ulimit -s unlimited

if [[ -f "EXIT" ]]
then
   rm EXIT
fi


mkdir tmpcp2k-$SLURM_ARRAY_TASK_ID
cd    tmpcp2k-$SLURM_ARRAY_TASK_ID

cp ../in.cp2k .
cp ../init.xyz .

srun -n $SLURM_NTASKS -c $SLURM_CPUS_PER_TASK cp2k.psmp -i  in.cp2k -o cp2k.out

cd ..


wait

