#!/bin/bash -l
#
# CP2K on Piz Daint: 64 nodes, 1 MPI task per node, 12 OpenMP threads per task
#
#SBATCH --job-name=cp2k
#SBATCH --time=18:50:00
#SBATCH --nodes=27
#SBATCH --ntasks-per-node=12
#SBATCH --cpus-per-task=1
#SBATCH --account=s904
#SBATCH --partition=normal
#SBATCH --constraint=gpu
#========================================
# load modules and run simulation


module load daint-gpu
module load CP2K
export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK:-1}
export CRAY_CUDA_MPS=1

ulimit -s unlimited

if [[ -f "EXIT" ]]
then
   rm EXIT
fi


if [[ ! -f "RUNNING" ]]
then
   touch RUNNING
   source ~/sources/i-pi/env.sh
   sed -i "s/HOST/$HOST/g" input.xml
   sed -i "s/HOSTN/$HOST/g" in.cp2k
   nohup ~/sources/i-pi/bin/i-pi input.xml > log &
   sleep 5
fi

sleep 5


mkdir tmpcp2k
cd    tmpcp2k

cp ../in.cp2k .
cp ../init.xyz .

srun -n $SLURM_NTASKS -c $SLURM_CPUS_PER_TASK cp2k.psmp -i  in.cp2k -o cp2k.out

cd ..


wait

rm RUNNING

