#!/bin/bash -l
#
# CP2K on Piz Daint: 64 nodes, 1 MPI task per node, 12 OpenMP threads per task
#
#SBATCH --job-name=traindeepmd
#SBATCH --time=4:50:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=12
#SBATCH --cpus-per-task=1
#SBATCH --account=em10
#SBATCH --partition=normal
#SBATCH --constraint=gpu
#========================================
# load modules and run simulation


module load daint-gpu
module use /apps/empa/apps/modules/all
module load deepmd-kit
export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK:-1}
export CRAY_CUDA_MPS=1

ulimit -s unlimited

export OMP_NUM_THREADS=12
export TF_INTRA_OP_PARALLELISM_THREADS=12
export TF_INTER_OP_PARALLELISM_THREADS=1

dp train example_train.json 

wait

